name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Show version
        run: echo "Version is $VERSION"

     - name: Update APP_VERSION
  run: |
    sed -i "s/value: \"v[0-9a-z]*\"/value: \"$VERSION\"/" web-deployment.yaml


      - name: Show updated deployment
        run: cat web-deployment.yaml
